---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo
  region: ap-northeast-1
  version: "1.13"

nodeGroups:
  - name: demo
    instanceType: m5.large
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        albIngress: true
