kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 31380
    hostPort: 31380
    listenAddress: "127.0.0.1"
    protocol: tcp
